--------------------------------------------------------
--  파일이 생성됨 - 화요일-6월-09-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMENTS
--------------------------------------------------------

   CREATE SEQUENCE  "DB_USER"."SEQ_COMMENTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_POSTS
--------------------------------------------------------

   CREATE SEQUENCE  "DB_USER"."SEQ_POSTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_POST_LIKES
--------------------------------------------------------

   CREATE SEQUENCE  "DB_USER"."SEQ_POST_LIKES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 18 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_POST_TAGS
--------------------------------------------------------

   CREATE SEQUENCE  "DB_USER"."SEQ_POST_TAGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TAGS
--------------------------------------------------------

   CREATE SEQUENCE  "DB_USER"."SEQ_TAGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOOKMARKS
--------------------------------------------------------

  CREATE TABLE "DB_USER"."BOOKMARKS" 
   (	"BOOKMARK_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" VARCHAR2(30 BYTE), 
	"POST_ID" NUMBER, 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "DB_USER"."COMMENTS" 
   (	"COMMENT_ID" NUMBER, 
	"POST_ID" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOLLOWS
--------------------------------------------------------

  CREATE TABLE "DB_USER"."FOLLOWS" 
   (	"FOLLOWER_ID" VARCHAR2(30 BYTE), 
	"FOLLOWING_ID" VARCHAR2(30 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSTS
--------------------------------------------------------

  CREATE TABLE "DB_USER"."POSTS" 
   (	"POST_ID" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"CODE_BLOCK" VARCHAR2(4000 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POST_LIKES
--------------------------------------------------------

  CREATE TABLE "DB_USER"."POST_LIKES" 
   (	"LIKE_ID" NUMBER, 
	"POST_ID" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POST_TAGS
--------------------------------------------------------

  CREATE TABLE "DB_USER"."POST_TAGS" 
   (	"POST_TAG_ID" NUMBER, 
	"POST_ID" NUMBER, 
	"TAG_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAGS
--------------------------------------------------------

  CREATE TABLE "DB_USER"."TAGS" 
   (	"TAG_ID" NUMBER, 
	"TAG_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DB_USER"."USERS" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"NICKNAME" VARCHAR2(30 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"PROFILE_IMAGE" VARCHAR2(500 BYTE), 
	"BIO" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DB_USER.BOOKMARKS
SET DEFINE OFF;
Insert into DB_USER.BOOKMARKS (BOOKMARK_ID,USER_ID,POST_ID,CREATED_AT) values (82,'user01',9,to_date('26/06/08','RR/MM/DD'));
Insert into DB_USER.BOOKMARKS (BOOKMARK_ID,USER_ID,POST_ID,CREATED_AT) values (81,'user01',4,to_date('26/06/08','RR/MM/DD'));
Insert into DB_USER.BOOKMARKS (BOOKMARK_ID,USER_ID,POST_ID,CREATED_AT) values (83,'user01',8,to_date('26/06/08','RR/MM/DD'));
Insert into DB_USER.BOOKMARKS (BOOKMARK_ID,USER_ID,POST_ID,CREATED_AT) values (84,'user01',6,to_date('26/06/08','RR/MM/DD'));
Insert into DB_USER.BOOKMARKS (BOOKMARK_ID,USER_ID,POST_ID,CREATED_AT) values (42,'hong123',9,to_date('26/06/07','RR/MM/DD'));
Insert into DB_USER.BOOKMARKS (BOOKMARK_ID,USER_ID,POST_ID,CREATED_AT) values (16,'hong123',8,to_date('26/06/05','RR/MM/DD'));
Insert into DB_USER.BOOKMARKS (BOOKMARK_ID,USER_ID,POST_ID,CREATED_AT) values (18,'hong123',6,to_date('26/06/05','RR/MM/DD'));
REM INSERTING into DB_USER.COMMENTS
SET DEFINE OFF;
Insert into DB_USER.COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT) values (1,4,'hong123','수정된 댓글입니다',to_date('26/06/01','RR/MM/DD'),to_date('26/06/01','RR/MM/DD'));
Insert into DB_USER.COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT) values (3,4,'hong123','댓글 테스트3',to_date('26/06/01','RR/MM/DD'),null);
Insert into DB_USER.COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT) values (5,4,'hong123','이게되네??!!',to_date('26/06/02','RR/MM/DD'),to_date('26/06/03','RR/MM/DD'));
Insert into DB_USER.COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT) values (4,4,'hong123','댓글 테스트4',to_date('26/06/02','RR/MM/DD'),null);
Insert into DB_USER.COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT) values (7,4,'hong123','zz',to_date('26/06/02','RR/MM/DD'),null);
Insert into DB_USER.COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT) values (8,4,'hong123','qq',to_date('26/06/02','RR/MM/DD'),null);
Insert into DB_USER.COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT) values (9,10,'user01','ㅋㅋㅋ',to_date('26/06/08','RR/MM/DD'),null);
REM INSERTING into DB_USER.FOLLOWS
SET DEFINE OFF;
Insert into DB_USER.FOLLOWS (FOLLOWER_ID,FOLLOWING_ID,CREATED_AT) values ('user01','hong123',to_date('26/06/08','RR/MM/DD'));
Insert into DB_USER.FOLLOWS (FOLLOWER_ID,FOLLOWING_ID,CREATED_AT) values ('hong123','user01',to_date('26/06/08','RR/MM/DD'));
REM INSERTING into DB_USER.POSTS
SET DEFINE OFF;
Insert into DB_USER.POSTS (POST_ID,USER_ID,TITLE,CONTENT,CODE_BLOCK,CREATED_AT,UPDATED_AT) values (8,'hong123','JavaScript 비동기 처리에서 async/await 사용하기','fetch 결과를 받아온 뒤 데이터를 사용해야 해서 await 사용','async function getUser() {
    try {
        const response = await fetch(''/api/user'');
        const data = await response.json();

        console.log(data);
    } catch (error) {
        console.error(''에러 발생:'', error);
    }
}',to_date('26/06/03','RR/MM/DD'),null);
Insert into DB_USER.POSTS (POST_ID,USER_ID,TITLE,CONTENT,CODE_BLOCK,CREATED_AT,UPDATED_AT) values (9,'hong123','구조 분해 할당','api에서 받은 데이터 중에 민감한 정보 버리고 나머지만 전역저장소(UserContext)에 저장하고 싶을때 쓰는거
data.userInfo의 배를 갈라서 비번 저장하는 컬럼만 꺼낸 후 나머지를 사용','if (data && data.userInfo) {
                const { PASSWORD_HASH, ...safeUserInfo } = data.userInfo;   
                setGlobalUserInfo(safeUserInfo);
            }',to_date('26/06/06','RR/MM/DD'),null);
Insert into DB_USER.POSTS (POST_ID,USER_ID,TITLE,CONTENT,CODE_BLOCK,CREATED_AT,UPDATED_AT) values (10,'user01','테스트','테스트','console.log("테스트")',to_date('26/06/08','RR/MM/DD'),null);
Insert into DB_USER.POSTS (POST_ID,USER_ID,TITLE,CONTENT,CODE_BLOCK,CREATED_AT,UPDATED_AT) values (4,'hong123','테스트3','내용3','console.log(''test3'')',to_date('26/06/01','RR/MM/DD'),null);
Insert into DB_USER.POSTS (POST_ID,USER_ID,TITLE,CONTENT,CODE_BLOCK,CREATED_AT,UPDATED_AT) values (6,'hong123','테스트5','내용5','console.log(''test5'')',to_date('26/06/02','RR/MM/DD'),null);
REM INSERTING into DB_USER.POST_LIKES
SET DEFINE OFF;
Insert into DB_USER.POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (4,4,'hong123',to_date('26/06/03','RR/MM/DD'));
Insert into DB_USER.POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (12,6,'hong123',to_date('26/06/06','RR/MM/DD'));
Insert into DB_USER.POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (13,9,'hong123',to_date('26/06/06','RR/MM/DD'));
Insert into DB_USER.POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (14,8,'user01',to_date('26/06/08','RR/MM/DD'));
Insert into DB_USER.POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (15,6,'user01',to_date('26/06/08','RR/MM/DD'));
Insert into DB_USER.POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (16,9,'user01',to_date('26/06/08','RR/MM/DD'));
Insert into DB_USER.POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (17,4,'user01',to_date('26/06/08','RR/MM/DD'));
Insert into DB_USER.POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (11,8,'hong123',to_date('26/06/05','RR/MM/DD'));
REM INSERTING into DB_USER.POST_TAGS
SET DEFINE OFF;
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (1,8,2);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (2,8,3);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (3,8,4);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (4,8,5);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (5,8,6);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (6,9,7);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (7,9,8);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (8,9,9);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (9,10,10);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (10,10,11);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (11,10,12);
Insert into DB_USER.POST_TAGS (POST_TAG_ID,POST_ID,TAG_ID) values (12,10,13);
REM INSERTING into DB_USER.TAGS
SET DEFINE OFF;
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (8,'UserContext');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (3,'async');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (4,'await');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (6,'backend');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (9,'createContext');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (13,'express');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (11,'java');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (2,'javascript');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (12,'oracle');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (5,'promise');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (10,'react');
Insert into DB_USER.TAGS (TAG_ID,TAG_NAME) values (7,'구조분해할당');
REM INSERTING into DB_USER.USERS
SET DEFINE OFF;
Insert into DB_USER.USERS (USER_ID,EMAIL,PASSWORD_HASH,NICKNAME,CREATED_AT,PROFILE_IMAGE,BIO) values ('user02','ys123@naver.com','$2b$10$j1OiSWKI8on.4UOBCByIwORGt5ckeMVNHciR9cR6i.CfPB0vuW.kW','yongsu',to_date('26/06/07','RR/MM/DD'),null,null);
Insert into DB_USER.USERS (USER_ID,EMAIL,PASSWORD_HASH,NICKNAME,CREATED_AT,PROFILE_IMAGE,BIO) values ('hong123','hong123@naver.com','$2b$10$AdGHT/B3eIQAefV3esqqeOI.Ch6wJBs314Nv9TZe7IJWVCGUCNF7.','KILLDONG',to_date('26/06/01','RR/MM/DD'),'http://localhost:3010/uploads/profiles/1780817896464-스크린샷 2026-05-01 121728.png','자바를 자바라 부르지 못하고~~~
리액트를 리액트라 부르지 못하고~~~');
Insert into DB_USER.USERS (USER_ID,EMAIL,PASSWORD_HASH,NICKNAME,CREATED_AT,PROFILE_IMAGE,BIO) values ('kong123','kong123@naver.com','$2b$10$U8b6BEEoXoLNeM8UuOleRe6ncrsRIAJC4aFz.WJi44gqlUgKhtwcK','KILLKONG',to_date('26/06/02','RR/MM/DD'),null,null);
Insert into DB_USER.USERS (USER_ID,EMAIL,PASSWORD_HASH,NICKNAME,CREATED_AT,PROFILE_IMAGE,BIO) values ('user01','ironwater@naver.com','$2b$10$U8b6BEEoXoLNeM8UuOleRe6ncrsRIAJC4aFz.WJi44gqlUgKhtwcK','김절수',to_date('26/06/02','RR/MM/DD'),null,'여러분 물 조심 하세요~');
--------------------------------------------------------
--  DDL for Index IDX_COMMENTS_POST
--------------------------------------------------------

  CREATE INDEX "DB_USER"."IDX_COMMENTS_POST" ON "DB_USER"."COMMENTS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_COMMENTS_USER
--------------------------------------------------------

  CREATE INDEX "DB_USER"."IDX_COMMENTS_USER" ON "DB_USER"."COMMENTS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_POSTS_CREATED_AT
--------------------------------------------------------

  CREATE INDEX "DB_USER"."IDX_POSTS_CREATED_AT" ON "DB_USER"."POSTS" ("CREATED_AT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_POSTS_USER
--------------------------------------------------------

  CREATE INDEX "DB_USER"."IDX_POSTS_USER" ON "DB_USER"."POSTS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOOKMARKS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."PK_BOOKMARKS" ON "DB_USER"."BOOKMARKS" ("BOOKMARK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FOLLOWS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."PK_FOLLOWS" ON "DB_USER"."FOLLOWS" ("FOLLOWER_ID", "FOLLOWING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008224
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008224" ON "DB_USER"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008231
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008231" ON "DB_USER"."POSTS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008234
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008234" ON "DB_USER"."TAGS" ("TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008238
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008238" ON "DB_USER"."POST_TAGS" ("POST_TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008246
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008246" ON "DB_USER"."COMMENTS" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008251
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008251" ON "DB_USER"."POST_LIKES" ("LIKE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_BOOKMARK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UK_BOOKMARK" ON "DB_USER"."BOOKMARKS" ("USER_ID", "POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_POST_TAGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UK_POST_TAGS" ON "DB_USER"."POST_TAGS" ("POST_ID", "TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_TAGS_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UK_TAGS_NAME" ON "DB_USER"."TAGS" ("TAG_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USERS_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UK_USERS_EMAIL" ON "DB_USER"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USERS_NICKNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UK_USERS_NICKNAME" ON "DB_USER"."USERS" ("NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_POST_USER_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UQ_POST_USER_LIKE" ON "DB_USER"."POST_LIKES" ("POST_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOOKMARKS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."PK_BOOKMARKS" ON "DB_USER"."BOOKMARKS" ("BOOKMARK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_BOOKMARK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UK_BOOKMARK" ON "DB_USER"."BOOKMARKS" ("USER_ID", "POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_COMMENTS_POST
--------------------------------------------------------

  CREATE INDEX "DB_USER"."IDX_COMMENTS_POST" ON "DB_USER"."COMMENTS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_COMMENTS_USER
--------------------------------------------------------

  CREATE INDEX "DB_USER"."IDX_COMMENTS_USER" ON "DB_USER"."COMMENTS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008246
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008246" ON "DB_USER"."COMMENTS" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FOLLOWS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."PK_FOLLOWS" ON "DB_USER"."FOLLOWS" ("FOLLOWER_ID", "FOLLOWING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_POSTS_CREATED_AT
--------------------------------------------------------

  CREATE INDEX "DB_USER"."IDX_POSTS_CREATED_AT" ON "DB_USER"."POSTS" ("CREATED_AT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_POSTS_USER
--------------------------------------------------------

  CREATE INDEX "DB_USER"."IDX_POSTS_USER" ON "DB_USER"."POSTS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008231
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008231" ON "DB_USER"."POSTS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008251
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008251" ON "DB_USER"."POST_LIKES" ("LIKE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_POST_USER_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UQ_POST_USER_LIKE" ON "DB_USER"."POST_LIKES" ("POST_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008238
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008238" ON "DB_USER"."POST_TAGS" ("POST_TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_POST_TAGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UK_POST_TAGS" ON "DB_USER"."POST_TAGS" ("POST_ID", "TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008234
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008234" ON "DB_USER"."TAGS" ("TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_TAGS_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UK_TAGS_NAME" ON "DB_USER"."TAGS" ("TAG_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008224
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."SYS_C008224" ON "DB_USER"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USERS_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UK_USERS_EMAIL" ON "DB_USER"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USERS_NICKNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_USER"."UK_USERS_NICKNAME" ON "DB_USER"."USERS" ("NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOKMARKS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."BOOKMARKS" MODIFY ("BOOKMARK_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."BOOKMARKS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."BOOKMARKS" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."BOOKMARKS" ADD CONSTRAINT "PK_BOOKMARKS" PRIMARY KEY ("BOOKMARK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_USER"."BOOKMARKS" ADD CONSTRAINT "UK_BOOKMARK" UNIQUE ("USER_ID", "POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."COMMENTS" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."COMMENTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."COMMENTS" ADD PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOLLOWS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."FOLLOWS" MODIFY ("FOLLOWER_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."FOLLOWS" MODIFY ("FOLLOWING_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."FOLLOWS" ADD CONSTRAINT "CHK_SELF_FOLLOW" CHECK (FOLLOWER_ID <> FOLLOWING_ID) ENABLE;
  ALTER TABLE "DB_USER"."FOLLOWS" ADD CONSTRAINT "PK_FOLLOWS" PRIMARY KEY ("FOLLOWER_ID", "FOLLOWING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSTS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."POSTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."POSTS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."POSTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."POSTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."POSTS" ADD PRIMARY KEY ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POST_LIKES
--------------------------------------------------------

  ALTER TABLE "DB_USER"."POST_LIKES" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."POST_LIKES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."POST_LIKES" ADD PRIMARY KEY ("LIKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_USER"."POST_LIKES" ADD CONSTRAINT "UQ_POST_USER_LIKE" UNIQUE ("POST_ID", "USER_ID")
  USING INDEX "DB_USER"."UQ_POST_USER_LIKE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POST_TAGS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."POST_TAGS" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."POST_TAGS" MODIFY ("TAG_ID" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."POST_TAGS" ADD PRIMARY KEY ("POST_TAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_USER"."POST_TAGS" ADD CONSTRAINT "UK_POST_TAGS" UNIQUE ("POST_ID", "TAG_ID")
  USING INDEX "DB_USER"."UK_POST_TAGS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAGS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."TAGS" MODIFY ("TAG_NAME" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."TAGS" ADD PRIMARY KEY ("TAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_USER"."TAGS" ADD CONSTRAINT "UK_TAGS_NAME" UNIQUE ("TAG_NAME")
  USING INDEX "DB_USER"."UK_TAGS_NAME"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."USERS" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."USERS" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."USERS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "DB_USER"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_USER"."USERS" ADD CONSTRAINT "UK_USERS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX "DB_USER"."UK_USERS_EMAIL"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKMARKS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."BOOKMARKS" ADD CONSTRAINT "FK_BOOKMARK_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "DB_USER"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DB_USER"."BOOKMARKS" ADD CONSTRAINT "FK_BOOKMARK_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "DB_USER"."POSTS" ("POST_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."COMMENTS" ADD CONSTRAINT "FK_COMMENTS_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "DB_USER"."POSTS" ("POST_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DB_USER"."COMMENTS" ADD CONSTRAINT "FK_COMMENTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "DB_USER"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOLLOWS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."FOLLOWS" ADD CONSTRAINT "FK_FOLLOWER" FOREIGN KEY ("FOLLOWER_ID")
	  REFERENCES "DB_USER"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "DB_USER"."FOLLOWS" ADD CONSTRAINT "FK_FOLLOWING" FOREIGN KEY ("FOLLOWING_ID")
	  REFERENCES "DB_USER"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POSTS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."POSTS" ADD CONSTRAINT "FK_POSTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "DB_USER"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST_LIKES
--------------------------------------------------------

  ALTER TABLE "DB_USER"."POST_LIKES" ADD CONSTRAINT "FK_LIKE_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "DB_USER"."POSTS" ("POST_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DB_USER"."POST_LIKES" ADD CONSTRAINT "FK_LIKE_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "DB_USER"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST_TAGS
--------------------------------------------------------

  ALTER TABLE "DB_USER"."POST_TAGS" ADD CONSTRAINT "FK_POST_TAGS_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "DB_USER"."POSTS" ("POST_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DB_USER"."POST_TAGS" ADD CONSTRAINT "FK_POST_TAGS_TAG" FOREIGN KEY ("TAG_ID")
	  REFERENCES "DB_USER"."TAGS" ("TAG_ID") ON DELETE CASCADE ENABLE;
